/**
 * Canonical LaTeX preamble + \\begin{document} for Muskan-style résumés.
 * One-page A4 density; explicit \\fontsize hierarchy (body 9.5/11, sections, header).
 */
export const MUSKAN_RESUME_PREAMBLE = [
  "\\documentclass[10pt,a4paper]{article}",
  "\\usepackage[utf8]{inputenc}",
  "\\usepackage[margin=0.35in]{geometry}",
  "\\usepackage{enumitem}",
  "\\usepackage{titlesec}",
  "\\usepackage{xcolor}",
  "\\usepackage{hyperref}",
  "\\usepackage{multicol}",
  "\\usepackage{array}",
  "\\usepackage{tabularx}",
  "",
  "% Remove page numbers",
  "\\pagestyle{empty}",
  "",
  "% Custom colors",
  "\\definecolor{primary}{RGB}{0, 102, 204}",
  "\\definecolor{secondary}{RGB}{51, 51, 51}",
  "",
  "% Section / subsection typography (explicit sizes; hierarchy vs 10pt body)",
  "\\titleformat{\\section}{\\fontsize{9.5}{11}\\selectfont\\bfseries\\color{primary}}{}{0em}{}[\\titlerule]",
  "\\titleformat{\\subsection}{\\fontsize{8.5}{10}\\selectfont\\bfseries\\color{secondary}}{}{0em}{}",
  "",
  "% Remove default spacing",
  "\\titlespacing*{\\section}{0pt}{1pt}{0pt}",
  "\\titlespacing*{\\subsection}{0pt}{0pt}{0pt}",
  "",
  "% Tight itemize (one-page friendly)",
  "\\setlist[itemize]{leftmargin=*,topsep=-3pt,itemsep=0pt,parsep=0pt,partopsep=0pt}",
  "",
  "% Remove default paragraph indentation",
  "\\setlength{\\parindent}{0pt}",
  "",
  "% Rupee symbol command",
  "\\newcommand{\\rupee}{Rs.}",
  "",
  "% Header (name 13pt; contact 8.5pt)",
  "\\newcommand{\\header}[3]{",
  "    \\begin{center}",
  "        {\\fontsize{13}{15}\\selectfont\\bfseries\\color{primary} #1}\\\\[0pt]",
  "        {\\fontsize{8.5}{10}\\selectfont #2}\\\\[0pt]",
  "        {\\fontsize{8.5}{10}\\selectfont #3}",
  "    \\end{center}",
  "    \\vspace{-2pt}",
  "}",
  "",
  "% Experience item (dates slightly smaller italic)",
  "\\newcommand{\\experience}[4]{",
  "    \\subsection{#1}",
  "    \\textbf{#2} \\hfill {\\fontsize{9}{10}\\selectfont\\itshape #3}\\\\",
  "    \\vspace{-10pt}",
  "    #4",
  "}",
  "",
  "% Project item",
  "\\newcommand{\\project}[3]{",
  "    \\subsection{#1 \\hfill \\textcolor{primary}{\\textbf{#2}}}",
  "    \\vspace{-2pt}",
  "    #3",
  "}",
  "",
  "% Set link colors",
  "\\hypersetup{",
  "    colorlinks=true,",
  "    linkcolor=primary,",
  "    urlcolor=primary,",
  "    citecolor=primary",
  "}",
  "",
  "% Fix hyperref warnings for \\hfill in PDF strings",
  "\\pdfstringdefDisableCommands{%",
  "    \\def\\hfill{ }%",
  "}",
  "",
  "\\begin{document}",
  "% Base body: slightly tighter than raw 10pt class (subsections/sections use titleformat sizes)",
  "\\fontsize{9.5}{11}\\selectfont",
].join("\n");
